### PR TITLE
Arm9select

### PR DESCRIPTION
**Pull request by fallenlucario**

### CODE REVIEW

**Comment by Reisyukaku** [comment]
wtf is this PR? lol

**Comment by ihaveamac** [comment]
it looks like all the changes in the "AuReiNand" fork

**Comment by fallenlucario** [comment]
I'm not sure how I can post an issue I'm having with Aureinand, when i try on their page it links me here. I didn't wanna post it here because I felt it was the wrong place.

**Comment by thedax** [comment]
@fallenlucario, if you have problems with ARN, just post about it in its respective thread on GBATemp.

**Pull request closed without merging**
