### PR TITLE
Minimized fatfs, removed unused file writing code moved mpu setup to emunand

### PR DESCRIPTION
**Pull request by ghost**
This should give a nice reduction to the overall size of arm9loaderhax.bin aka removing **code bloat :3**

### CODE REVIEW

**Comment by Reisyukaku** [comment]
removing that 'bloat' makes it completely inflexible. I do like to write files as well for debugging purposes.

**Comment by ghost** [comment]
Then keep your Debug and Compiled build separate? Sure you may need to debug but the userbase doesn't that should be optional entirely. Just set the flags alread

**Comment by daedreth** [comment]
x3

**Comment by ghost** [comment]
x3

**Comment by Seriell** [comment]
x3

**Comment by Supster131** [comment]
x3

**Comment by ThatNerdyPikachu** [comment]
x3

**Pull request closed without merging**
